# Generated by Django 5.2.7 on 2025-10-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macarrones', '0002_alter_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='propic',
            field=models.ImageField(blank=True, default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
